version: '3.8'

services:
  video-face-blur:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./web_temp_uploads:/app/web_temp_uploads
      - ./static:/app/static
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
